# Generated by Django 2.0.7 on 2018-07-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
