# Generated by Django 2.0.7 on 2018-07-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20180725_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Music.Album'),
        ),
    ]
